# Generated by Django 2.2.3 on 2019-08-18 13:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190817_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parentid',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(choices=[(2, 'L'), (3, 'XL'), (40, '40 Beden'), (0, 'XS'), (36, '36 Beden'), (34, '34 Beden'), (1, 'M')]),
        ),
    ]
