# Generated by Django 2.2.3 on 2019-08-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20190818_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(choices=[(36, '36 Beden'), (3, 'XL'), (40, '40 Beden'), (2, 'L'), (34, '34 Beden'), (0, 'XS'), (1, 'M')]),
        ),
    ]
