# Generated by Django 2.2.3 on 2019-08-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20190818_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.IntegerField(choices=[(1, 'True'), (0, 'False')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(choices=[(36, '36 Beden'), (3, 'XL'), (2, 'L'), (1, 'M'), (0, 'XS'), (40, '40 Beden'), (34, '34 Beden')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(1, 'True'), (0, 'False')]),
        ),
    ]
