# Generated by Django 2.2.3 on 2019-08-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20190822_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(choices=[(2, 'L'), (34, '34 Beden'), (0, 'XS'), (1, 'M'), (40, '40 Beden'), (36, '36 Beden'), (3, 'XL')]),
        ),
    ]
