# Generated by Django 2.2.3 on 2019-08-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20190822_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.IntegerField(choices=[(1, 'True'), (0, 'False')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(choices=[(3, 'XL'), (2, 'L'), (36, '36 Beden'), (40, '40 Beden'), (0, 'XS'), (1, 'M'), (34, '34 Beden')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(1, 'True'), (0, 'False')]),
        ),
    ]
