# Generated by Django 2.2.3 on 2019-08-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20190822_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(choices=[(36, '36 Beden'), (0, 'XS'), (1, 'M'), (40, '40 Beden'), (2, 'L'), (3, 'XL'), (34, '34 Beden')]),
        ),
    ]
