# Generated by Django 2.2.3 on 2019-08-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20190822_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(choices=[(36, '36 Beden'), (34, '34 Beden'), (1, 'M'), (2, 'L'), (0, 'XS'), (40, '40 Beden'), (3, 'XL')]),
        ),
    ]
