# Generated by Django 2.2.3 on 2019-08-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20190823_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(choices=[(2, 'L'), (0, 'XS'), (36, '36 Beden'), (40, '40 Beden'), (3, 'XL'), (34, '34 Beden'), (1, 'M')]),
        ),
    ]
