# Generated by Django 2.2.3 on 2019-08-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20190823_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(choices=[(36, '36 Beden'), (34, '34 Beden'), (40, '40 Beden'), (2, 'L'), (1, 'M'), (3, 'XL'), (0, 'XS')]),
        ),
    ]
