# Generated by Django 2.2.3 on 2019-08-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20190823_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(choices=[(40, '40 Beden'), (34, '34 Beden'), (3, 'XL'), (36, '36 Beden'), (2, 'L'), (0, 'XS'), (1, 'M')]),
        ),
    ]
