# Generated by Django 2.2.3 on 2019-08-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20190823_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.IntegerField(choices=[(0, 'False'), (1, 'True')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(choices=[(2, 'L'), (36, '36 Beden'), (0, 'XS'), (1, 'M'), (34, '34 Beden'), (40, '40 Beden'), (3, 'XL')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(0, 'False'), (1, 'True')]),
        ),
    ]
