# Generated by Django 2.2.3 on 2019-08-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20190823_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.IntegerField(choices=[(0, 'False'), (1, 'True')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(choices=[(36, '36 Beden'), (2, 'L'), (40, '40 Beden'), (1, 'M'), (0, 'XS'), (3, 'XL'), (34, '34 Beden')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(0, 'False'), (1, 'True')]),
        ),
    ]
