# Generated by Django 2.2.3 on 2019-08-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20190824_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(choices=[(3, 'XL'), (36, '36 Beden'), (2, 'L'), (1, 'M'), (0, 'XS'), (40, '40 Beden'), (34, '34 Beden')]),
        ),
    ]
