# Generated by Django 2.2.3 on 2019-08-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_auto_20190827_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(choices=[(0, 'XS'), (40, '40 Beden'), (34, '34 Beden'), (1, 'M'), (2, 'L'), (36, '36 Beden'), (3, 'XL')]),
        ),
    ]
