# Generated by Django 2.2.3 on 2019-08-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_auto_20190827_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(choices=[(40, '40 Beden'), (0, 'XS'), (1, 'M'), (36, '36 Beden'), (2, 'L'), (3, 'XL'), (34, '34 Beden')]),
        ),
    ]
