# Generated by Django 2.2.3 on 2019-08-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_auto_20190827_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(choices=[(34, '34 Beden'), (36, '36 Beden'), (0, 'XS'), (1, 'M'), (2, 'L'), (40, '40 Beden'), (3, 'XL')]),
        ),
    ]
