# Generated by Django 2.2.3 on 2019-08-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_auto_20190827_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(choices=[(40, '40 Beden'), (36, '36 Beden'), (3, 'XL'), (0, 'XS'), (34, '34 Beden'), (1, 'M'), (2, 'L')]),
        ),
    ]
