# Generated by Django 2.2.3 on 2019-08-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_orderdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OnShipping', 'OnShipping'), ('Accepted', 'Accepted'), ('Refused', 'Refused'), ('NEW', 'New'), ('Completed', 'Completed'), ('Preparing', 'Preparing')], default='New', max_length=15),
        ),
    ]
