# Generated by Django 2.2.3 on 2019-08-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20190823_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Refused', 'Refused'), ('Completed', 'Completed'), ('OnShipping', 'OnShipping'), ('NEW', 'New'), ('Preparing', 'Preparing')], default='New', max_length=15),
        ),
    ]
