# Generated by Django 2.2.3 on 2019-08-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20190824_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OnShipping', 'OnShipping'), ('Preparing', 'Preparing'), ('Accepted', 'Accepted'), ('Refused', 'Refused'), ('NEW', 'New'), ('Completed', 'Completed')], default='New', max_length=15),
        ),
    ]
