# Generated by Django 2.2.3 on 2019-08-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20190827_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('OnShipping', 'OnShipping'), ('Refused', 'Refused'), ('Accepted', 'Accepted'), ('Preparing', 'Preparing'), ('NEW', 'New')], default='New', max_length=15),
        ),
    ]
