# Generated by Django 2.2.3 on 2019-08-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20190827_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Accepted', 'Accepted'), ('NEW', 'New'), ('Refused', 'Refused'), ('Preparing', 'Preparing'), ('OnShipping', 'OnShipping')], default='New', max_length=15),
        ),
    ]
