# Generated by Django 2.2.3 on 2019-08-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20190827_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Preparing', 'Preparing'), ('Refused', 'Refused'), ('OnShipping', 'OnShipping'), ('NEW', 'New'), ('Completed', 'Completed')], default='New', max_length=15),
        ),
    ]
