# Generated by Django 2.2.3 on 2019-08-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_auto_20190827_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OnShipping', 'OnShipping'), ('Refused', 'Refused'), ('Accepted', 'Accepted'), ('Preparing', 'Preparing'), ('NEW', 'New'), ('Completed', 'Completed')], default='New', max_length=15),
        ),
    ]
