# Generated by Django 2.2.3 on 2019-08-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_auto_20190827_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('OnShipping', 'OnShipping'), ('Completed', 'Completed'), ('Refused', 'Refused'), ('Preparing', 'Preparing'), ('NEW', 'New')], default='New', max_length=15),
        ),
    ]
